/* SQLCMD bootstrap for an EMPTY Nicole database. Run from repository root. */
:r database/tables/00-create-table-entitystatus.sql
:r database/tables/01-create-table-identification-type.sql
:r database/tables/02-create-table-person-type.sql
:r database/seeds/00-seed-base-catalogs.sql
:r database/tables/03-create-table-person.sql
:r database/tables/04-create-table-company.sql
:r database/tables/05-create-table-company-branch.sql
:r database/tables/06-create-table-company-emission-point.sql
:r database/tables/08-create-table-profile.sql
:r database/tables/07-create-table-app-user.sql
:r database/tables/11-create-table-user-profile.sql
:r database/tables/12-create-table-user-profile-audit.sql
:r database/tables/09-create-table-permission.sql
:r database/seeds/01-seed-base-permissions.sql
:r database/tables/10-create-table-profile-permission.sql
:r database/tables/13-create-table-global-client-registry.sql
:r database/tables/20-create-table-client.sql
:r database/seeds/20260905_003_centralizar_registro_global_clientes_permissions.sql
:r database/procedures/catalogs/P_Catalog_Lookup.sql
:r database/procedures/auth/P_Auth_Register.sql
:r database/procedures/auth/P_Auth_GetSessionContext.sql
:r database/procedures/auth/P_Auth_Login.sql
:r database/procedures/auth/P_User_Create.sql
:r database/procedures/auth/P_User_Update.sql
:r database/procedures/auth/P_User_SetStatus.sql
:r database/procedures/auth/P_User_List.sql
:r database/procedures/profile/P_Permission_List.sql
:r database/procedures/profile/P_ProfilePermission_ReplaceByProfile.sql
:r database/procedures/profile/P_Profile_Create.sql
:r database/procedures/profile/P_Profile_Deactivate.sql
:r database/procedures/profile/P_Profile_GetDetail.sql
:r database/procedures/profile/P_Profile_ListByCompany.sql
:r database/procedures/profile/P_Profile_Update.sql
:r database/procedures/profile/P_UserProfile_Assign.sql
:r database/procedures/profile/P_UserProfile_Revoke.sql
:r database/procedures/profile/P_UserProfile_ListByUser.sql
:r database/procedures/registry-client/20260905_006_registry_client_authorization_helpers.sql
:r database/procedures/registry-client/20260905_001_usp_person_resolve_identification.sql
:r database/procedures/registry-client/20260905_003_usp_client_create.sql
:r database/procedures/registry-client/20260905_004_usp_client_update.sql
:r database/procedures/registry-client/20260905_005_usp_client_deactivate.sql
:r database/security/20260905_001_centralizar_registro_global_clientes_grants.sql
